### ISSUE TITLE
dlib.network.url under OSX

### ISSUE THREAD

**Issue by gecko0307** [gecko0307/dlib#102]
Tests in `dlib.network.url` fail to pass under OSX:

`core.exception.AssertError@dlib/network/url.d(1206): http://127.0.0.1/`

**Comment by gecko0307** [comment]
I doubt this is caused by C-style conversion (tried both atoi and strtoul). Don't have Mac, so this is really problematic for me to fix.

**Comment by MyLittleRobo** [comment]
My guess it's because memory for string is already freed at this time. parseURL create URL on stack and upon function exit its destructor free all parsed components. Somehow Linux is ok with it, while OS X does not.

**Comment by MyLittleRobo** [comment]
Does URL need to allocate at all? I think we're on same boat here as with Lexer.

**Comment by gecko0307** [comment]
Seems working now.
