### ISSUE TITLE
allocators and event loop

### ISSUE THREAD

**Issue by belka-ew** [gecko0307/dlib#110]
I've just finished a simple event loop implementation. It works currently only on linux but other platforms can be added in the future.

I also wrote an allocator for the event loop, since malloc wouldn't be enough, it requires a memory pool to be performant.

Would be cool if you would be agree to extend dlib in another direction aswell (networking). And I wanted to ask aswell what do you think about allocators? I see it as a great possibility to abstract the memory management. People can choose to use gc or manual memory management, where both is possible. it would imho solve the problem with throwing the exceptions in no-gc code. I could write more if you're interested.

I also started to work on a lightweight tls implementation. There is some math and a few crypto algorithms, but I have a long way beyond me regarding this.

**Comment by gecko0307** [comment]
Do you mean porting dlib to `std.experimental.allocator`? I find its API somewhat ugly. Passing `IAllocator` objects everywhere when you want to allocate something is not very convenient. Of course, we can just store one global allocator that can be switched to GC or non-GC implementation, but that can be easily done independently from Phobos. I'm actually planning to do it in near future.
Event loop would be cool. It can use its own allocation strategy, that's not a problem.

**Comment by belka-ew** [comment]
I don't like everything about std.experimental.allocator either. 

1.  My original idea was to pass IAllocator everywhere as the last argument and set its default to theAllocator or processAllocator.

  So the function that allocate would look like:
  ```d
  void myFunct(int arg1, char arg2, IAllocator allocator = processAllocator);
  ```
  It is the most flexible way:
  - If anybody wants to use the default allocator, processAllocator/theAllocator can be set and it will be used everywhere since it is the default value everywhere.
  - And if another allocator should be used somewhere, the allocator can be passed and override the default one.

  The problem is, as you say, that the allocator should be specified almost everywhere.

2. It could be better just to use theAllocator/processAllocator everywhere without passing it to every single function/class, since using one allocator here and another one there could cause problems anyway.

3. - Instead of IAllocator we could use an own allocator interface (IAllocator has imho too many methods that are not really needed). Phobos allocators don't implement the Interface directly anyway. But if we use our own  Interface, I would keep it compatible with IAllocator just to increase compatibility between different libraries. It means that the allocator should have methods allocate/deallocate and they should have the same signature as IAllocator.
  - The same: if we use anown Allocator Interface, we can define something like defaultAllocator property instead of theAllocator/processAllocator, which can be set by the user and is called from everywhere then.

I don't know what is better, but it is what I find reasonable. If I understand correctly, you would combine 2) and 3)?

And I would create a separate package for all the stuff and maybe move core.memory slowly to it. dlib.memory?

**Comment by gecko0307** [comment]
Yes, I think 2) and 3) are the way to go, probably with one global allocator per module / package.

**Comment by belka-ew** [comment]
If you don't mind I would submit the event loop in steps. I need make some adjustments, before I can push everything. For example I wrote some containers (Queue, List and two buffer classes) and I would switch to dlib.container. So I would suggest that we first work out how we handle allocators and then I can make a pull request for the rest.
Do you think we can use functions from std.experimental.allocator (make,dispose, shrink/expandArray and so on) or create our own implementations?

**Comment by gecko0307** [comment]
As long as they are templated and compatible with our Allocator, I think it's nothing wrong with using them.
