### ISSUE TITLE
Unittest console output

### ISSUE THREAD

**Issue by belka-ew** [gecko0307/dlib#120]
Every time I run unittests I get a long output with the list of all *.d files in the directories and "Hello, World!" at the end.
It is a bit distirbing if I want to output something temporary and should scroll every time to see the output. Maybe put all the outputs into a version block like `version (VerboseUnittest)`?

**Comment by gecko0307** [comment]
IIRC, this is one of the unittests in dlib.filesystem. It can be rewritten to scan only one directory to reduce the output.

**Comment by belka-ew** [comment]
yes, dlib.filesystem.local on two places. The first unittest makes only output and no asserts. The secound unittest makes some checks.
Can I rewrite these unit tests so that the result of the dlib functions is compared with the result of std.file functions (or maybe ls, stat commands)? It would make this console output superfluous and the unit tests would be better, since you haven't to verify the results manually anymore.

**Comment by belka-ew** [comment]
Fixed with #121.
