### ISSUE TITLE
dlib.container redesign

### ISSUE THREAD

**Issue by belka-ew** [gecko0307/dlib#123]
I would like to propose some changes to dlib.container and discuss if they would make sense:
- Integrating of dlib.memory allocators
- Making the containers more Phobos and D-ranges conform. It would make the use of containers simpler if the naming conventions would be consistent. Therefore I think it would make sense to use `insertBack`, `insertFront` and so on for the appropriate operations.
- Introducing of some operator overloading for ease of use (for example `~=` for appending the values).
- Introducing dlib.container.vector (or Vector in dlib.container.array). Same as dlib.container.array but without the static storage.
# Allocators

I would not use `dlib.memory.defaultAllocator` (or containerAllocator) for the containers but pass the allocator as the last argument to the constructor of each container. Containers are very generic data structures and I can think of use cases where you want to use containers with different allocators. The one I'm thinking about is the crypto package that will need a kind of SecureAllocator, which will reset the memory with sensitive data before deallocating, but the event loop needs the Queue with a different allocator. It is only an example, here can be other use cases.
# Phobos and D-ranges

For example `dlib.container.linkedlist` defines methods like `insertBeginning`, `append`, `removeBeginning`, `search`. `insertBeginning` is always called `insertFront` everywhere, `append` -> `insertBack`, `removeBeginning` -> `removeFront`, `search` -> `find`. The same can be done for other containers. As I sayed these names would simplify the use of the library because you haven't to look every time into the source code to find out the name of the method you need. The old method names can be aliased to the new ones and maybe deprecated.
# Vector

The static storage makes it difficult to implement the slicing ([a..b]) efficiently.

---
All that things I can do myself. But I want to ask if these changes would be desirable and if there are other ideas before beginning the actual work.

**Comment by gecko0307** [comment]
I like these ideas, but we would need non-TLS allocator first. I recently stumbled across this problem:  `dlib.core.thread` doesn't support thread local storage (i.e., all global variables should be marked with `__gshared` for correct access from plain C threads), so it seems that threads in their current implementation can't be used with `Mallocator`. I use this thread module in my other projects depending on dlib (and I heavily use containers in threads, for that matter), so it's a critical issue for me. I'm not sure if TLS API for pthreads/windows threads can talk with with D's internal data sharing logics.

**Comment by gecko0307** [comment]
A bit off topic, but... It becomes clear for me that dlib gradually becomes somewhat ugly. I once decided to make it fully GC-free, and maybe some of my architectural decisions weren't thought out. Some part of dlib is D-way, some is not, Phobos-compatible stuff is mixed with Phobos-incompatible. Many important things are actually wrappers around C APIs, and not all of them match well with the outer world.

**Comment by belka-ew** [comment]
Ugly code isn't bad. Ok, it is bad, but every codebase that exists for some time becomes ugly. There is nothing to do about it, but update the code and hope that the new ugly code is less ugly than the old one.
imho creating a fork will cause more work to do, maintaining two repositories, merging changes and so on. And the existing dlib-based projects could help to test new features in dlib and to see if these features/changes help to improve the workflow in the real projects.
I really don't want to break anything of your code. Maybe there is a more gentle way.
* splitting the tasks and making changes in more little steps and testing between the particular steps
* opening a branch for breaking changes. Testing the branch and only after that merging it into the master

Regarding TLS I'm currently working only on single-threaded application, but the using of multiple threads would improve performance, so it is something interesting to look in to. The only problem I'm not very experianced in multithreading programming yet.
I tried to design the `Mallocator` compatible with `New` and `Delete`. Are there problems with `New` and `Delete` aswell or only with the allocator?
What do you mean under a non-TLS allocator? Do you have some more details on implementing it?
Is the problematic code open source? can you point me to places where the allocation and threading don't work well, so I can test if I get some ideas?
Maybe we can steal some more code from druntime.

**Comment by gecko0307** [comment]
The main problem is that `New` and `Delete` use a global variable to keep track of total allocated memory (`_allocatedMemory`). By default all global variables in D are treated in a special way to work with multithreading - they are copied to thread-local memory and use implicit synchronisation for shared access. For compatibility with С, there is `__gshared` keyword that is used to store the variable in the classic global data segment. GC-free threads in `dlib.core.thread` only work with `__gshared` globals. If we make a global instance of `Mallocator` as an underlying backend for `New` and `Delete`, it should also be marked as `__gshared`, but this would at least require serious API changes in `dlib.memory`. Recently I've tried to do this for curiosity, but found that `atomicOp` from Phobos requires the data to be `shared`. Atomic operations are used in `dlib.memory.mmappool`, which I honestly still don't dare to touch =)
Returning to `New` and `Delete`, the allocation counter is not a strictly required thing, but it's a nice leak debugging tool which I don't want to lose. Making a fork only to keep it is not the best solution, of course. One possible workaround is a compile-time condition to switch to conservative `New`/`Delete`, but that again will strongly complicate things. If there was a way to use local allocator instances, the problem would not exist, but this can't be implemented without total API break all across the library.

**Comment by belka-ew** [comment]
Ah ok. I think atomic operations can be just removed from the `MmapPool` for now and replaced with simple `+=` and `-=`, since the allocator isn't thread safe anyway and won't work in multi-threaded code. It will just require an another method for synchronization across the threads to make it thread-safe.

Btw. dmd 2.072.0 is out. There are few compilation errors, some in my code and some in `dlib.filesystem` and `dlib.text` I think I will prepare a pull request in the next days

**Comment by belka-ew** [comment]
Ok, I'm beginning to understand what's going on. My idea with shared(Allocator) doesn't seem to work. It works only for D code.
Slowly I begin to beleive that we could go for std.experimental.allocator. I'm also not happy about all design decisions of Phobos allocators, but Phobos has
* `processAllocator` which can return a __gshared allocator object (set in shared static this() of the module).
* `threadAllocator` (set in static this() of the module)
* `GCAllocator` which can be used without writing our own
* `IAllocator` which is pretty the same as the allocator interface I have written + some methods that will be mostly unused.

I just would let the allocators implement IAllocator instead of using `std.experimental.allocator.allocatorObject` and use threadAllocator/processAllocator instead of `dlib.memory.defaultAllocator`. And I would already add an `exceptionAllocator` so the user always now how to free the thrown exceptions.
Other way we end up rewriting the same what Phobos already can without any advantage.
And breaking dlib.memory isn't a problem imho. It wasn't released, so there is no API-breakage. It is better to fix it now than too late.

**Comment by belka-ew** [comment]
So I removed `shared` from everywhere to make it usable with `__gshared`. I think you can use `processAllocator` where you need a __gshared allocator.
See `container-allocator` branch in my fork: https://github.com/belka-ew/dlib/tree/container-allocator/dlib/memory
@gecko0307, do you think it is something we can work with?

**Comment by belka-ew** [comment]
@gecko0307 ping. Should I make a pull request for one container (e.g. LinkedList), so we could experiment?

**Comment by gecko0307** [comment]
Lately I haven't enough time to work on dlib, but now I decided to address this issue, so reopening.

**Comment by gecko0307** [comment]
Just to inform about the status of this: while everything seems to work, allocation counter in `dlib.core.memory` shows wrong numbers in threaded applications. I haven't done any in-depth tests yet, just tried to run some of my projects using `Mallocator` at the backend. Will investigate this soon.

**Comment by gecko0307** [comment]
Finally I've fixed it, so dlib.memory-based `New` and `Delete` are coming now...

**Comment by gecko0307** [comment]
Returning to containers: I'll make method names more Phobos-conforming, but I don't see a point for Vector, since DynamicArray uses either static or dynamic storage, but never both. Actual array is itself a slice of them, it can be retrieved with `data` method. So there are no problems with slices. The reason behind static storage is efficiency when dealing with small data, such as short strings.
