### ISSUE TITLE
feature request: midi

### ISSUE THREAD

**Issue by SingingBush** [gecko0307/dlib#131]
any plans for handling midi protocol?

**Comment by gecko0307** [comment]
Do you mean only decoding MIDI files or playback also? It's not obvious how to do it under non-Windows OSes. It would require implementing a software synthesizer.

**Comment by SingingBush** [comment]
both midi files and midi devices. I was hoping to make use of an old Roland keyboard I have. In the past I've used C# when working with midi, I'd like to have another go at it using D

**Comment by gecko0307** [comment]
Seems too domain-specific, so I'm closing this FR for now.
It is not obvious how much of a music sequencer feature set should be implemented for adequate MIDI support. We can decode a file, but into what exactly? MIDI notes can be rendered differently depending on an instrument engine, there is no generic standard for that, and emulating hardware or adding pre-recorded samples are out of the question.
Capturing MIDI also requires too specific machinery that is outside the scope of dlib.
