### ISSUE TITLE
Support SVG images

### ISSUE THREAD

**Issue by icibiri** [gecko0307/dlib#141]

**Comment by gecko0307** [comment]
Closing this FR as impractical.
SVG is a huge standard that supports a lot of features that are not trivial to implement properly without third-party libraries (and efficiently without hardware acceleration). `dlib.image.canvas` is not sufficient to implement SVG, we need more powerful graphics pipeline for that, but [I decided not to turn dlib into a graphics engine from the start](https://github.com/gecko0307/dlib/wiki/Rationale).
It would be possible to implement only a subset of SVG, for rendering plain vector shapes, but for such cases using SVG seems excessive, this can be done directly with `dlib.image.canvas`. And the whole point of SVG is data exchange between different programs, so it's not reasonable to write a loader that won't fully support SVG files from any editing software.
