### ISSUE TITLE
SIMD in Vector, Matrix

### ISSUE THREAD

**Issue by minexew** [gecko0307/dlib#15]
(following the previous conversation...)
I also believe we should pay extra attention to leave our back door open for a possible SIMD implementation in the future. The way I imagine it, as SIMD isn't practical everywhere, would be through another template parameter. An example probably illustrates it better:
```
vec4 doWhatever(const ref vec4 data, const ref mat4 matrix) {
    // convert to SIMD types
    vec4sse data_simd = data;     // alias for Vector!(4, float, Vector.SSE)
    mat4sse matrix_simd = matrix;    // Matrix!(4, float, Vector.SSE)

    // now do some really complex and expensive operation
    ...

    // convert back to plain ol' floats and return
    return data_simd;
}
```

**Comment by gecko0307** [comment]
Recently I've began experimenting with this, I already have working SSE-based dot and cross product - about 50% faster than current implementation!

**Comment by gecko0307** [comment]
Committed my work in 3a7077b. Lacks subtraction, division, dot3, cross4 and vector-matrix multiplication.
