### ISSUE TITLE
Audio module

### ISSUE THREAD

**Issue by Dmunch04** [gecko0307/dlib#167]
Hi.

How am I supposed to create a new GenericSound instance with almost the exact same values as another one (loaded using `loadWAV`)? The new instance just ends up having an empty array of data, as it doesn't ininitalize that in the constructor.

Thanks,
Daniel

**Comment by Dmunch04** [comment]
It seems like the `GenericSound.stream` function should do that? Altough it never assigns the data?

**Comment by Dmunch04** [comment]
It seems like in order to write the data in the stream function, this should be reversed;
```
buffer[i] = _data[i];
```

I might be wrong

**Comment by Dmunch04** [comment]
Nevermind that actually won't fix it

**Comment by gecko0307** [comment]
`GenericSound.dup()` does exactly that

**Comment by Dmunch04** [comment]
That wasn't what I was trying to do. Altough I got this to work for me:
```d
foreach (i; 0 .. originalSound.size)
{
     newSound[0, i] = originalSound[1, i];
}
```
The snippet is from https://github.com/AODQ/aoynthesizer/blob/master/source/app.d

**Comment by gecko0307** [comment]
Oh I see. If you want to copy data to another channe, or use another sample format, then yes, that is the only way to do it.

**Comment by Dmunch04** [comment]
Alright. Thanks. I thought stream was the function to do so, altough I was mistaken. The wiki for the audio module could probably use an example or 2.

Anyway thanks for your help! I'll close the issue as it's been resolved
