### ISSUE TITLE
Query string

### ISSUE THREAD

**Issue by 89z** [gecko0307/dlib#175]
It seems this package can parse a URL, but cannot parse a query string into a map, or vice versa. Is that correct?

**Comment by gecko0307** [comment]
Yes, query is not parsed yet, unfortunately.

**Comment by 89z** [comment]
Workaround:

- https://urllibparse.dpldocs.info/urllibparse.parseQS.html
- https://urllibparse.dpldocs.info/urllibparse.urlEncode.1.html
