### ISSUE TITLE
Can't open jpg images with "Progressive DCT, Huffman coding" encoding

### ISSUE THREAD

**Issue by al1-ce** [gecko0307/dlib#180]
Tried out several JPEG images but those which was problematic always had progressive dct encoding where others was just fine.
I'm attaching archive with one's throwing exception.
[UnableToOpen.zip](https://github.com/gecko0307/dlib/files/8101255/UnableToOpen.zip)

**Comment by gecko0307** [comment]
Progressive JPEGs are not supported yet.
