### ISSUE TITLE
More examples in the domument

### ISSUE THREAD

**Issue by LukyGuyLucky** [gecko0307/dlib#187]
This is great and I like it very much!

Would be appreciated if more examples( just pieces of code snippets) to show the usage of the APIs,say,how to load and play a WAV file or how to load a BMP file and show in the screen,etc.

Thanks and best regards.

**Comment by gecko0307** [comment]
Thank you for the feedback! There are a number of usage examples [on the project's website](https://gecko0307.github.io/dlib/), including an example of loading an image. As for displaying images on the screen and playing sounds, dlib does not currently provide such functionality. For this you can use a multimedia library such as SDL.

**Comment by LukyGuyLucky** [comment]
Thank you!
