### ISSUE TITLE
Implement the most efficient HashMap in the world

### ISSUE THREAD

**Issue by minexew** [gecko0307/dlib#19]
We don't seem to have one, or is my eyesight getting bad?

**Comment by minexew** [comment]
It certainly was an ambitious plan, but I don't think I'll get around to doing it anytime soon.
Besides, D's associative arrays have seen significant improvement since then, haven't they?

**Comment by gecko0307** [comment]
I agree. There is `dlib.container.dict` now, but it is oriented more to genericity than speed. If someone needs higher performance, he will likely end up with some specialized solution.
