### ISSUE TITLE
Normals of frustum's planes are pointing inside frustum

### ISSUE THREAD

**Issue by MrSmith33** [gecko0307/dlib#43]
I found that plane normals of frustum are pointing inside frustum, while common solution is to make them point outside. Maybe it will be better to make them point outside to minimize confusion?
![frustum](https://cloud.githubusercontent.com/assets/1129910/5756754/9f28c912-9cbb-11e4-95dc-6e84e5894175.png)

**Comment by gecko0307** [comment]
Yes, it would be reasonable.
