### ISSUE TITLE
unittest build failed

### ISSUE THREAD

**Issue by buggins** [gecko0307/dlib#47]
travis-ci unittest build for my project dlangide fails on dlib:

Building dlib 0.4.1 configuration "library", build type unittest.
Running dmd...
../../../.dub/packages/dlib-0.4.1/dlib/filesystem/local.d(341): Error: function dlib.filesystem.local.findFiles (string baseDir, bool recursive) is not callable using argument types (ReadOnlyFileSystem, string, bool)
../../../.dub/packages/dlib-0.4.1/dlib/filesystem/local.d(361): Error: undefined identifier 'functions'
../../../.dub/packages/dlib-0.4.1/dlib/filesystem/local.d(363): Error: undefined identifier 'functions'
../../../.dub/packages/dlib-0.4.1/dlib/math/vector.d(948): Warning: calling dlib.math.vector.Vector!(float, 3).Vector.length without side effects discards return value of type float, prepend a cast(void) if intentional
../../../.dub/packages/dlib-0.4.1/dlib/math/vector.d(949): Warning: calling dlib.math.vector.Vector!(float, 3).Vector.lengthsqr without side effects discards return value of type float, prepend a cast(void) if intentional
../../../.dub/packages/dlib-0.4.1/dlib/math/vector.d(950): Warning: calling dlib.math.vector.distance!float.distance without side effects discards return value of type float, prepend a cast(void) if intentional
FAIL ../../../.dub/packages/dlib-0.4.1/.dub/build/library-unittest-linux.posix-x86_64-dmd_2066-C3294255E83FD63DEF449B07C61958D9/ dlib staticLibrary
Error executing command test: dmd failed with exit code 1.

**Comment by gecko0307** [comment]
I have the same errors with dlib.filesystem.local on DMD 2.067-b1 (already fixed them, actually), but not with dlib.math.vector. What version are you using?

**Comment by minexew** [comment]
What did they change that it broke that UFCS?

**Comment by gecko0307** [comment]
Does it compile now?

**Comment by Extrawurst** [comment]
unittests work now, but can you tag this 0.4.2 or something so that travis testing dlangIDE works again ?
see: https://github.com/buggins/dlangide/pull/16

**Comment by gecko0307** [comment]
There're breaking changes since 0.4.1, so it will be 0.5.0 when #49 will be fixed.
