### ISSUE TITLE
Filed to build unittest configuration under x64 compiler

### ISSUE THREAD

**Issue by buggins** [gecko0307/dlib#52]
lve@vlopatin-laptop:~/src/d/dlib$ dub build --build=unittest
Building dlib 0.4.1+commit.34.gebd7d7c configuration "library", build type unittest.
Running dmd...
dlib/core/oop.d(174): Warning: use '{ }' for an empty statement, not a ';'
dlib/core/oop.d(180): Warning: use '{ }' for an empty statement, not a ';'
dlib/core/oop.d(185): Warning: use '{ }' for an empty statement, not a ';'
dlib/container/array.d(70): Error: None of the overloads of 'append' are callable using argument types (int), candidates are:
dlib/container/array.d(89):        dlib.container.array.DynamicArray!(HuffmanTableEntry, 32LU).DynamicArray.append(HuffmanTableEntry c)
dlib/container/array.d(118):        dlib.container.array.DynamicArray!(HuffmanTableEntry, 32LU).DynamicArray.append(const(HuffmanTableEntry)[] s)
dlib/container/array.d(85): Error: cannot implicitly convert expression (0) of type int to HuffmanTableEntry
dlib/image/io/jpeg.d(153): Error: template instance dlib.container.array.DynamicArray!(HuffmanTableEntry, 32LU) error instantiating
FAIL .dub/build/library-unittest-linux.posix-x86_64-dmd_2066-2961EB2D0079E9BB12186E96CBA5D5F0/ dlib staticLibrary
Error executing command build: dmd failed with exit code 1.

**Comment by gecko0307** [comment]
The issue with dlib.container.array was my bad, I've uploaded wrong file. But I don't get any warnings about dlib.core.oop. How it is now?
