### ISSUE TITLE
Add vec <-> ivec convertion

### ISSUE THREAD

**Issue by MrSmith33** [gecko0307/dlib#57]
Would be nice to have an easy way to convert one type to another through constructor.
like `ivec3 discretePos = ivec3(vec3var);` or maybe with `to!ivec3(vec3Var);`

Currently I use 
```
ivec3 toivec3(vec3 vec)
{
	return ivec3(cast(int)vec.x, cast(int)vec.y, cast(int)vec.z);
}
```

**Comment by MrSmith33** [comment]
Thanks

**Comment by gecko0307** [comment]
You're welcome =)
It now supports not only conversion by constructor, but also direct assignment: `ivec3 discretePos = vec3var`

**Comment by MrSmith33** [comment]
Can you also add casts to:
https://github.com/gecko0307/dlib/blob/master/dlib/math/vector.d#L93
https://github.com/gecko0307/dlib/blob/master/dlib/math/vector.d#L77
https://github.com/gecko0307/dlib/blob/master/dlib/math/vector.d#L82
