### ISSUE TITLE
Doesn't Build on Mac

### ISSUE THREAD

**Issue by GanMatt** [gecko0307/dlib#68]
dlib/math/sse.d(184): Error: bad type/size of operands 'mov'
FAIL .dub/build/library-debug-posix.osx-x86_64-dmd_2066-5F283B0B6A1DC5388B277615AB841C18/ dlib staticLibrary
Error executing command run: dmd failed with exit code 1.

**Comment by gecko0307** [comment]
That's a serious problem. Unfortunately, I don't have Mac to fix this. Maybe just put the module under `version`?

**Comment by GanMatt** [comment]
I have no idea what you mean with that suggestion but I say go for it.

**Comment by minexew** [comment]
I haven't touched D in months (no pun intended), but that code looks like it's assuming a 32-bit architecture. That's why it's impossible to move a pointer into EAX on a 64-bit OS.

**Comment by minexew** [comment]
Using RAX instead of EAX in 64-bit mode should do the job.

**Comment by gecko0307** [comment]
Indeed the problem was with EAX/RAX, thank you minexew. I have absolutely zero experience with 64-bit systems, should read more documentation.
