### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by olehlong** [gecko0307/dlib#74]
DMD64 D Compiler v2.068.0
dlib - 0.6.2
Linux

/dlib/filesystem/stdfs.d(73): Error: function core.stdc.stdio.fseek (shared(_IO_FILE)* stream, long offset, int whence) is not callable using argument types (shared(_IO_FILE)*, fpos_t, int)
/dlib/math/vector.d(525): Warning: int *= float is performing truncating conversion
/dlib/math/vector.d(525): Warning: uint *= float is performing truncating conversion
/dlib/math/vector.d(525): Warning: int *= float is performing truncating conversion
/dlib/math/vector.d(525): Warning: uint *= float is performing truncating conversion
/dlib/math/vector.d(525): Warning: int *= float is performing truncating conversion
/dlib/math/vector.d(525): Warning: uint *= float is performing truncating conversion
/dlib/math/vector.d(525): Warning: ushort *= float is performing truncating conversion

**Comment by gecko0307** [comment]
This has been already fixed in master (#73). Are you using 0.6.2? If so, I'll make a new release.

**Comment by olehlong** [comment]
yes. 0.6.2 is the latest release in dub

**Comment by gecko0307** [comment]
Done. Should appear in dub registry soon.
