### ISSUE TITLE
GC-free findFiles

### ISSUE THREAD

**Issue by gecko0307** [gecko0307/dlib#86]
`dlib.filesystem.stdfs` should provide an unmanaged version of `findFiles`, a function that allows to traverse a directory in `ReadOnlyFileSystem` recursively.

**Comment by minexew** [comment]
Sorry for not taking up my responsibility with this function (if it is the one I wrote), but I haven't written any D in over a year.

**Comment by gecko0307** [comment]
Your `findFiles` is okay, it's just would be nice to have full-featured GC-free implementation of `dlib.filesystem.filesystem`. I don't think these two implementations should intersect in any way.
