### ISSUE TITLE
Web functions

### ISSUE THREAD

**Issue by belka-ew** [gecko0307/dlib#91]
Hi,

I'm doing some web development. And slowly I have more functions that are pretty general. Mostly these are text parsing routines: URL parsing, IP-Address validating and stuff like this. Since I like the idea of dlib to create a generic library with additional functionality, I want to suggest to add some web stuff to it, but I'm not sure if it is something, dlib would be interested in.

My first candidate would be a function that parses an URL-string and splits it into serveral parts (scheme, host, path, query string and so on): https://github.com/caraus-ecms/caraus/blob/master/source/caraus/lib/url.d#L637
It doesn't depend on something else and if you would accept it I would get a rid of using the GC and make a pull request.

What do you think?

**Comment by gecko0307** [comment]
It would be nice to have networking and web stuff, but ideally it should be Phobos-independent, with manual memory management and dlib's containers instead of native ones.

**Comment by belka-ew** [comment]
no problem. I just wanted to have "ok" from you before I make my code depend on dlib. I will rewrite then parts where I use Phobos and probably I will need some guidance by you for the first time :) since I haven't worked with dlib before.
Will try to make a pull request in the next days, so you can review it.

**Comment by belka-ew** [comment]
I've rewritten GC parts. Functions from std.ascii and std.uni are marked as nogc in phobos. Only unit tests relying on GC now, don't know if it is bad.
There are pretty much unit tests. It is because URL parsing wasn't that easy as I thought before. So there are different test cases, I used

**Comment by belka-ew** [comment]
And as I see from travis, it doesn't work on Mac and I don't have any Mac here. Maybe because I used stroul from C instead of std.conv.to. Can you check if it will pass the tests with a newer DMD on Mac?

**Comment by gecko0307** [comment]
Added DMD 2.071.0, they still fail. I've created an issue for this: #102.

**Comment by belka-ew** [comment]
Thanks for your fixes. I'll see if I have other similar stuff and will just create pull requests. I think this ticket can be closed.

P.S.: One thing I have forgotten is to add some information about the package to the README. And I really don't know what I could write. So you may add a small generic description.
And can you please make a new release soon? There were a lot of changes lately...
