### ISSUE TITLE
Lexer does not lex the last lexeme

### ISSUE THREAD

**Issue by MyLittleRobo** [gecko0307/dlib#96]
```d
auto input = "for (int i=0;";
auto lexer = new Lexer(input, ["(", ")", ";", " ", "="]);
import std.stdio;
while(!lexer.eos()) {
    auto lexeme = lexer.getLexeme();
    writeln("lexeme: ", lexeme);
    Delete(lexeme);
}
```

Will not print ";" lexeme.

Note: If some other delimiter is met right before the last, then the output includes ";" too. E.g.:

```d
auto input = "for (int i=0);";
```

**Comment by gecko0307** [comment]
You are using it incorrectly. `getLexeme` returns empty string at the end of an input, so it should be something like that:

```d
dchar[] lexeme;
while(true)
{
    lexeme = lexer.getLexeme();

    if (!lexeme.length)
        break;

    writeln("lexeme: ", lexeme);
    Delete(lexeme);
}
```
I know, it is somewhat counter-intuitive, so there is a room for improvements.

**Comment by MyLittleRobo** [comment]
I think the best way is to add InputRange interface for this task.

**Comment by gecko0307** [comment]
I've added a separate issue for that task, closing this one.
