### ISSUE TITLE
InputRange interface for Lexer

### ISSUE THREAD

**Issue by gecko0307** [gecko0307/dlib#98]
`dlib.text.lexer.Lexer` should implement `std.range.interfaces.InputRange`.

**Comment by gecko0307** [comment]
Oh, my bad, I haven't noticed that this is already done in 1171cf73fbfdc394f5dc99f97923e049277d54e5.

**Comment by MyLittleRobo** [comment]
The problem is that InputRange interface is almost unusable because you need to explicitly free things. One can't easily do chained calls without leaking memory.

**Comment by MyLittleRobo** [comment]
Also I don't think it should implement directly this interface. Just conformity to InputRange concept would be enough.
