### ISSUE TITLE
Lexer can avoid allocations at all

### ISSUE THREAD

**Issue by MyLittleRobo** [gecko0307/dlib#99]
The current implementation of Lexer takes input and delims as parameters. All these things are already pre-allocated by user code, no matter how, via GC or alternative allocator. The only job of Lexer is to break input in parts, so it does not need allocate strings itself.

Lexer can be agnostic of how strings were allocated so user would get the full control over memory allocation. 

This is breaking change though because Lexer will not more return unmanaged dchar[], but slices of original input instead.

(Note that this idea works as long as Lexer gets the full input. The general lexer implementation would require general input, e.g. InputStream)

Also this change will affect XML parser. Btw XML parser could be done without string allocations too (it still needs to allocate nodes though), but that would require input to be mutable. That's how popular C++ library rapidxml works. Mutating is needed to insert zero-characters to make strings zero-terminated and to convert xml entities. The first is not problem in D, since we can use slices of original input. Entities though does not allow reusing the same data, since data needs to be changed on entity parsing. If not entities xml parsing may work on immutable data without string allocations too.

**Comment by gecko0307** [comment]
I like this idea, lexer this way would be significantly faster. I will definitely implement this.
